In [7]:
import pandas as pd
data = pd.read_csv ("REU end use data.csv")
data.head()

,Location ID,Start Time,End Time,Event,Volume (gal),Duration (min)
0,110510,2024-11-13 15:00:55.000,2024-11-13 15:01:00.000,FAUCET,0.034632,0.083333
1,110510,2024-11-13 16:58:55.000,2024-11-13 16:59:00.000,FAUCET,0.034632,0.083333
2,110510,2024-11-13 18:03:55.000,2024-11-13 18:04:00.000,FAUCET,0.034632,0.083333
3,110510,2024-11-13 19:36:35.000,2024-11-13 19:36:40.000,FAUCET,0.034632,0.083333
4,110510,2024-11-13 21:35:30.000,2024-11-13 21:35:35.000,FAUCET,0.034632,0.083333

In [10]:
unique_enduses = data['Event'].unique()
print(unique_enduses)

<StringArray>
[        'FAUCET',         'SHOWER',         'TOILET', 'CLOTHES_WASHER',
         'INDOOR',     'IRRIGATION',           'LEAK',    'DISH_WASHER',
        'OUTDOOR',       'SOFTENER',            'TUB']
Length: 11, dtype: str

In [13]:
data['avgflow (gal/min)'] = data['Volume (gal)'] / data['Duration (min)']

In [14]:
data.head()

,Location ID,Start Time,End Time,Event,Volume (gal),Duration (min),avgflow (gal/min)
0,110510,2024-11-13 15:00:55.000,2024-11-13 15:01:00.000,FAUCET,0.034632,0.083333,0.415584
1,110510,2024-11-13 16:58:55.000,2024-11-13 16:59:00.000,FAUCET,0.034632,0.083333,0.415584
2,110510,2024-11-13 18:03:55.000,2024-11-13 18:04:00.000,FAUCET,0.034632,0.083333,0.415584
3,110510,2024-11-13 19:36:35.000,2024-11-13 19:36:40.000,FAUCET,0.034632,0.083333,0.415584
4,110510,2024-11-13 21:35:30.000,2024-11-13 21:35:35.000,FAUCET,0.034632,0.083333,0.415584

In [15]:
X, y = (data[['avgflow (gal/min)', 'Duration (min)']], data['Event'])

In [17]:
X

         avgflow (gal/min)  Duration (min)
0                 0.415584        0.083333
1                 0.415584        0.083333
2                 0.415584        0.083333
3                 0.415584        0.083333
4                 0.415584        0.083333
...                    ...             ...
9526024           0.871524       20.000000
9526025           0.879264       20.000000
9526026           0.933444       20.000000
9526027           0.806508       20.000000
9526028           3.729227        6.000000

[9526029 rows x 2 columns]

In [18]:
y

0              FAUCET
1              FAUCET
2              FAUCET
3              FAUCET
4              FAUCET
              ...
9526024    IRRIGATION
9526025    IRRIGATION
9526026    IRRIGATION
9526027    IRRIGATION
9526028    IRRIGATION
Name: Event, Length: 9526029, dtype: str

In [19]:
from sklearn.naive_bayes import GaussianNB